services:
  web:
    container_name: my_sample
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    #command: bash -c "rm -f /rails/tmp/pids/server.pid"
    volumes:
      - .:/rails
    depends_on:
      - db
    tty: true
    stdin_open: true
    working_dir: '/rails'

  db:
    image: postgres:16.8
    container_name: my_sample_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_volume:
